/*
 * generated by Xtext 2.17.0
 */
package dume.compiler.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDumeScopeProvider extends DelegatingScopeProvider {
}
