/*
 * generated by Xtext 2.17.0
 */
package dume.compiler.ide

import com.google.inject.Guice
import dume.compiler.DumeRuntimeModule
import dume.compiler.DumeStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class DumeIdeSetup extends DumeStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new DumeRuntimeModule, new DumeIdeModule))
	}
	
}
