/*
 * generated by Xtext 2.17.0
 */
package dume.compiler.ui.tests;

import com.google.inject.Injector;
import dume.compiler.ui.internal.CompilerActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class DumeUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CompilerActivator.getInstance().getInjector("dume.compiler.Dume");
	}

}
