/*
 * generated by Xtext 2.17.0
 */
package dume.compiler


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DumeStandaloneSetup extends DumeStandaloneSetupGenerated {

	def static void doSetup() {
		new DumeStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
