/**
 * generated by Xtext 2.17.0
 */
package dume.compiler.ui.contentassist;

import dume.compiler.ui.contentassist.AbstractDumeProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DumeProposalProvider extends AbstractDumeProposalProvider {
}
