/**
 * generated by Xtext 2.17.0
 */
package dume.compiler.validation;

import dume.compiler.validation.AbstractDumeValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DumeValidator extends AbstractDumeValidator {
}
