/**
 * generated by Xtext 2.17.0
 */
package dume.compiler.ide;

import dume.compiler.ide.AbstractDumeIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DumeIdeModule extends AbstractDumeIdeModule {
}
