/**
 * generated by Xtext 2.17.0
 */
package dume.compiler.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import dume.compiler.DumeRuntimeModule;
import dume.compiler.DumeStandaloneSetup;
import dume.compiler.ide.DumeIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class DumeIdeSetup extends DumeStandaloneSetup {
  @Override
  public Injector createInjector() {
    DumeRuntimeModule _dumeRuntimeModule = new DumeRuntimeModule();
    DumeIdeModule _dumeIdeModule = new DumeIdeModule();
    return Guice.createInjector(Modules2.mixin(_dumeRuntimeModule, _dumeIdeModule));
  }
}
