/*
 * generated by Xtext 2.17.0
 */
package dume.compiler.ui;

import com.google.inject.Injector;
import dume.compiler.ui.internal.CompilerActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DumeExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(CompilerActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		CompilerActivator activator = CompilerActivator.getInstance();
		return activator != null ? activator.getInjector(CompilerActivator.DUME_COMPILER_DUME) : null;
	}

}
