/*
 * generated by Xtext 2.17.0
 */
package dume.compiler.parser.antlr;

import com.google.inject.Inject;
import dume.compiler.parser.antlr.internal.InternalDumeParser;
import dume.compiler.services.DumeGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DumeParser extends AbstractAntlrParser {

	@Inject
	private DumeGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDumeParser createParser(XtextTokenStream stream) {
		return new InternalDumeParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Scripts";
	}

	public DumeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DumeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
