/**
 * generated by Xtext 2.17.0
 */
package dume.compiler.ui;

import dume.compiler.ui.AbstractDumeUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DumeUiModule extends AbstractDumeUiModule {
  public DumeUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
