/**
 * generated by Xtext 2.17.0
 */
package dume.compiler;

import dume.compiler.DumeStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DumeStandaloneSetup extends DumeStandaloneSetupGenerated {
  public static void doSetup() {
    new DumeStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
