/**
 * generated by Xtext 2.17.0
 */
package dume.compiler;

import dume.compiler.AbstractDumeRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DumeRuntimeModule extends AbstractDumeRuntimeModule {
}
