/**
 * generated by Xtext 2.17.0
 */
package dume.compiler.dume;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Circle</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dume.compiler.dume.Circle#getPoint <em>Point</em>}</li>
 *   <li>{@link dume.compiler.dume.Circle#getRadius <em>Radius</em>}</li>
 *   <li>{@link dume.compiler.dume.Circle#getMap <em>Map</em>}</li>
 * </ul>
 *
 * @see dume.compiler.dume.DumePackage#getCircle()
 * @model
 * @generated
 */
public interface Circle extends Shape
{
  /**
   * Returns the value of the '<em><b>Point</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Point</em>' containment reference.
   * @see #setPoint(Point2D)
   * @see dume.compiler.dume.DumePackage#getCircle_Point()
   * @model containment="true"
   * @generated
   */
  Point2D getPoint();

  /**
   * Sets the value of the '{@link dume.compiler.dume.Circle#getPoint <em>Point</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Point</em>' containment reference.
   * @see #getPoint()
   * @generated
   */
  void setPoint(Point2D value);

  /**
   * Returns the value of the '<em><b>Radius</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Radius</em>' attribute.
   * @see #setRadius(int)
   * @see dume.compiler.dume.DumePackage#getCircle_Radius()
   * @model
   * @generated
   */
  int getRadius();

  /**
   * Sets the value of the '{@link dume.compiler.dume.Circle#getRadius <em>Radius</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Radius</em>' attribute.
   * @see #getRadius()
   * @generated
   */
  void setRadius(int value);

  /**
   * Returns the value of the '<em><b>Map</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Map</em>' attribute.
   * @see #setMap(String)
   * @see dume.compiler.dume.DumePackage#getCircle_Map()
   * @model
   * @generated
   */
  String getMap();

  /**
   * Sets the value of the '{@link dume.compiler.dume.Circle#getMap <em>Map</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Map</em>' attribute.
   * @see #getMap()
   * @generated
   */
  void setMap(String value);

} // Circle
