/**
 * generated by Xtext 2.17.0
 */
package dume.compiler.dume;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Clear</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dume.compiler.dume.DumePackage#getClear()
 * @model
 * @generated
 */
public interface Clear extends Instruction
{
} // Clear
