/**
 * generated by Xtext 2.17.0
 */
package dume.compiler.dume;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Go</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dume.compiler.dume.Go#getPoint <em>Point</em>}</li>
 * </ul>
 *
 * @see dume.compiler.dume.DumePackage#getGo()
 * @model
 * @generated
 */
public interface Go extends Instruction
{
  /**
   * Returns the value of the '<em><b>Point</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Point</em>' containment reference.
   * @see #setPoint(Point)
   * @see dume.compiler.dume.DumePackage#getGo_Point()
   * @model containment="true"
   * @generated
   */
  Point getPoint();

  /**
   * Sets the value of the '{@link dume.compiler.dume.Go#getPoint <em>Point</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Point</em>' containment reference.
   * @see #getPoint()
   * @generated
   */
  void setPoint(Point value);

} // Go
