/**
 * generated by Xtext 2.17.0
 */
package dume.compiler.dume;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Loop</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dume.compiler.dume.Loop#getN <em>N</em>}</li>
 *   <li>{@link dume.compiler.dume.Loop#getInstructions <em>Instructions</em>}</li>
 * </ul>
 *
 * @see dume.compiler.dume.DumePackage#getLoop()
 * @model
 * @generated
 */
public interface Loop extends Instruction
{
  /**
   * Returns the value of the '<em><b>N</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>N</em>' attribute.
   * @see #setN(int)
   * @see dume.compiler.dume.DumePackage#getLoop_N()
   * @model
   * @generated
   */
  int getN();

  /**
   * Sets the value of the '{@link dume.compiler.dume.Loop#getN <em>N</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>N</em>' attribute.
   * @see #getN()
   * @generated
   */
  void setN(int value);

  /**
   * Returns the value of the '<em><b>Instructions</b></em>' containment reference list.
   * The list contents are of type {@link dume.compiler.dume.Instruction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Instructions</em>' containment reference list.
   * @see dume.compiler.dume.DumePackage#getLoop_Instructions()
   * @model containment="true"
   * @generated
   */
  EList<Instruction> getInstructions();

} // Loop
