/**
 * generated by Xtext 2.17.0
 */
package dume.compiler.dume;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Point2 D</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dume.compiler.dume.Point2D#getI <em>I</em>}</li>
 *   <li>{@link dume.compiler.dume.Point2D#getJ <em>J</em>}</li>
 *   <li>{@link dume.compiler.dume.Point2D#getMap <em>Map</em>}</li>
 * </ul>
 *
 * @see dume.compiler.dume.DumePackage#getPoint2D()
 * @model
 * @generated
 */
public interface Point2D extends Point
{
  /**
   * Returns the value of the '<em><b>I</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>I</em>' containment reference.
   * @see #setI(dume.compiler.dume.Number)
   * @see dume.compiler.dume.DumePackage#getPoint2D_I()
   * @model containment="true"
   * @generated
   */
  dume.compiler.dume.Number getI();

  /**
   * Sets the value of the '{@link dume.compiler.dume.Point2D#getI <em>I</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>I</em>' containment reference.
   * @see #getI()
   * @generated
   */
  void setI(dume.compiler.dume.Number value);

  /**
   * Returns the value of the '<em><b>J</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>J</em>' containment reference.
   * @see #setJ(dume.compiler.dume.Number)
   * @see dume.compiler.dume.DumePackage#getPoint2D_J()
   * @model containment="true"
   * @generated
   */
  dume.compiler.dume.Number getJ();

  /**
   * Sets the value of the '{@link dume.compiler.dume.Point2D#getJ <em>J</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>J</em>' containment reference.
   * @see #getJ()
   * @generated
   */
  void setJ(dume.compiler.dume.Number value);

  /**
   * Returns the value of the '<em><b>Map</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Map</em>' attribute.
   * @see #setMap(String)
   * @see dume.compiler.dume.DumePackage#getPoint2D_Map()
   * @model
   * @generated
   */
  String getMap();

  /**
   * Sets the value of the '{@link dume.compiler.dume.Point2D#getMap <em>Map</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Map</em>' attribute.
   * @see #getMap()
   * @generated
   */
  void setMap(String value);

} // Point2D
