/**
 * generated by Xtext 2.17.0
 */
package dume.compiler.dume;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Positive</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dume.compiler.dume.DumePackage#getPositive()
 * @model
 * @generated
 */
public interface Positive extends dume.compiler.dume.Number
{
} // Positive
