/**
 * generated by Xtext 2.17.0
 */
package dume.compiler.dume;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Shape2 D</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dume.compiler.dume.Shape2D#getMap <em>Map</em>}</li>
 *   <li>{@link dume.compiler.dume.Shape2D#getPoints <em>Points</em>}</li>
 * </ul>
 *
 * @see dume.compiler.dume.DumePackage#getShape2D()
 * @model
 * @generated
 */
public interface Shape2D extends Shape
{
  /**
   * Returns the value of the '<em><b>Map</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Map</em>' attribute.
   * @see #setMap(String)
   * @see dume.compiler.dume.DumePackage#getShape2D_Map()
   * @model
   * @generated
   */
  String getMap();

  /**
   * Sets the value of the '{@link dume.compiler.dume.Shape2D#getMap <em>Map</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Map</em>' attribute.
   * @see #getMap()
   * @generated
   */
  void setMap(String value);

  /**
   * Returns the value of the '<em><b>Points</b></em>' containment reference list.
   * The list contents are of type {@link dume.compiler.dume.Point2D}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Points</em>' containment reference list.
   * @see dume.compiler.dume.DumePackage#getShape2D_Points()
   * @model containment="true"
   * @generated
   */
  EList<Point2D> getPoints();

} // Shape2D
