/**
 * generated by Xtext 2.17.0
 */
package dume.compiler.dume;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Shape3 D</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dume.compiler.dume.Shape3D#getPoints <em>Points</em>}</li>
 * </ul>
 *
 * @see dume.compiler.dume.DumePackage#getShape3D()
 * @model
 * @generated
 */
public interface Shape3D extends Shape
{
  /**
   * Returns the value of the '<em><b>Points</b></em>' containment reference list.
   * The list contents are of type {@link dume.compiler.dume.Point3D}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Points</em>' containment reference list.
   * @see dume.compiler.dume.DumePackage#getShape3D_Points()
   * @model containment="true"
   * @generated
   */
  EList<Point3D> getPoints();

} // Shape3D
