/**
 * generated by Xtext 2.17.0
 */
package dume.compiler.dume;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Shape</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dume.compiler.dume.DumePackage#getShape()
 * @model
 * @generated
 */
public interface Shape extends EObject
{
} // Shape
